image: continuumio/miniconda3:latest

before_script:
#   - apt-get install -y conda cmake valgrind
  - apt-get update -q -y
  - apt-get install -y build-essential
  - apt-get install -y libgl1-mesa-glx # conda opencv
  - conda info -a
  - conda env create -n test-environment -f env.yml
  - source activate test-environment
  - python --version
  - conda install flake8 pydocstyle pylint

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
    - flake8 --exclude=pybind11,gps

pylint:
  stage: Static Analysis
  script:
    - cd gascamcontrol
    - pylint --ignore=pybind11 gascamcontrol

pydocstyle:
  stage: Static Analysis
  script:
    - pydocstyle

doctest:
  stage: Test
  script:
    - python -m doctest -v gascamcontrol/*.py gascamcontrol/devices/*/*.py gascamcontrol/plugins/*.py

#
#
#  clang-tidy
#  cppcheck
#  cpplint
#  iwyu
#
