image: continuumio/miniconda3:latest

before_script:
#   - apt-get install -y cmake valgrind
  - apt-get update -q -y
  - apt-get install -y build-essential cppcheck cmake
  - apt-get install -y libgl1-mesa-glx # conda opencv
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - conda info -a
  - conda env create -n test-environment -f environment.yml
  - source activate test-environment
  - python --version

stages:
  - Static Analysis
  - Test
  - Coverage

flake8:
  stage: Static Analysis
  script:
    - make flake8

pylint:
  stage: Static Analysis
  script:
    - make pylint

pycodestyle:
  stage: Static Analysis
  script:
    - make pycodestyle

pydocstyle:
  stage: Static Analysis
  script:
    - make pydocstyle

cppcheck:
  stage: Static Analysis
  script:
    - make cppcheck

cpplint:
  stage: Static Analysis
  script:
    - make cpplint

doctest:
  stage: Test
  script:
    - make doctest

pytest:
  stage: Test
  script:
    - make pytest

conda-env:
  stage: Test
  script:
    - make test_environment

conda-packages:
  stage: Test
  script:
    - make test_environment

coverage:
  stage: Coverage
  coverage: '/TOTAL.+?(\d+)%/'
  script:
    - make coverage
