channels:
  - conda-forge

dependencies:
  - python>=3.6
  - configargparse
  - opencv
  - matplotlib
  - numpy
  - aiohttp
  - pytest
  - flake8
  - pydocstyle
  - pylint
  - colorlog
  - cpplint
  - pytest-cov
  - pycodestyle
