{% set data = load_setup_py_data() %}

package:
  name: gascamcontrol
  version: {{ data.get('version') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  git_url: ../

requirements:     # (optional)
  build:
    - python=3.6
    - colorlog
    - aiohttp
    - numpy
    - configargparse
    - opencv
    - matplotlib
    - aiohttp

  run:
    - python=3.6
    - colorlog
    - aiohttp
    - numpy
    - configargparse
    - opencv
    - matplotlib
    - aiohttp


test:
  commands:
    - gascamcontrol --version
  imports:
    - gascamcontrol
  source_files:
    - gascamcontrol/plugins
